name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rust-fmt:
    name: Rust Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  rust-core-tests:
    name: Rust Core Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test
        run: cargo test --all --verbose

  build-snapshot:
    name: Build Snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install bsdtar
        run: sudo apt-get update && sudo apt-get install -y libarchive-tools

      - name: Build Snapshot
        run: ./scripts/build-default-snapshot.sh


